import React, { useState } from "react";
import UserContext from "./UserContext";
import Demoimage from "../image/demoimage.jpg";

const UserContextProvider = ({ children }) => {
  const [priceRange, setPriceRang] = useState();
  const [category, setCategory] = useState();
  const [cartItem, setCartItem] = useState([]);
  const [quantity, setQuantity] = useState([]);
  const [products, setProducts] = useState([
    {
      id: 1,
      title: "Graphic T-Shirt",
      price: "199",
      category: "clothing",
      description: "Comfortable cotton T-shirt with cool graphics for casual style.",
      image: Demoimage,
    },
    {
      id: 2,
      title: "Denim Jeans",
      price: "799",
      category: "clothing",
      description: "Classic blue denim jeans with a slim fit.",
      image: Demoimage,
    },
    {
      id: 3,
      title: "Hooded Sweatshirt",
      price: "599",
      category: "clothing",
      description: "Cozy hoodie with front pocket for chilly days.",
      image: Demoimage,
    },
    {
      id: 4,
      title: "Formal Shirt",
      price: "450",
      category: "clothing",
      description: "Elegant formal shirt for office wear or formal events.",
      image: Demoimage,
    },
    {
      id: 5,
      title: "Summer Shorts",
      price: "299",
      category: "clothing",
      description: "Breathable shorts perfect for summer activities.",
      image: Demoimage,
    },
    {
      id: 6,
      title: "Casual Jacket",
      price: "1200",
      category: "clothing",
      description: "Stylish casual jacket suitable for all seasons.",
      image: Demoimage,
    },
    {
      id: 7,
      title: "Track Pants",
      price: "550",
      category: "clothing",
      description: "Comfortable track pants for workouts or lounging.",
      image: Demoimage,
    },
    {
      id: 8,
      title: "Cap",
      price: "150",
      category: "clothing",
      description: "Cool baseball cap to complete your casual look.",
      image: Demoimage,
    },
    {
      id: 9,
      title: "Leather Belt",
      price: "300",
      category: "clothing",
      description: "Durable leather belt with a classic design.",
      image: Demoimage,
    },
    {
      id: 10,
      title: "Wool Sweater",
      price: "700",
      category: "clothing",
      description: "Warm wool sweater for cold weather.",
      image: Demoimage,
    },
    {
      id: 11,
      title: "Polo Shirt",
      price: "350",
      category: "clothing",
      description: "Casual polo shirt with a comfortable fit.",
      image: Demoimage,
    },
    {
      id: 12,
      title: "Raincoat",
      price: "800",
      category: "clothing",
      description: "Waterproof raincoat to stay dry on rainy days.",
      image: Demoimage,
    },
    {
      id: 13,
      title: "Socks (Pack of 5)",
      price: "120",
      category: "clothing",
      description: "Soft and durable socks for everyday wear.",
      image: Demoimage,
    },
    {
      id: 14,
      title: "Leather Jacket",
      price: "3000",
      category: "clothing",
      description: "High-quality leather jacket for a stylish look.",
      image: Demoimage,
    },
    {
      id: 15,
      title: "Joggers",
      price: "600",
      category: "clothing",
      description: "Comfortable joggers for casual outings or gym wear.",
      image: Demoimage,
    },
  
    {
      id: 16,
      title: "Smartphone",
      price: "12999",
      category: "electronics",
      description: "Latest model smartphone with high-resolution camera.",
      image: Demoimage,
    },
    {
      id: 17,
      title: "Bluetooth Headphones",
      price: "1999",
      category: "electronics",
      description: "Wireless headphones with noise-canceling feature.",
      image: Demoimage,
    },
    {
      id: 18,
      title: "Smartwatch",
      price: "4999",
      category: "electronics",
      description: "Stylish smartwatch with fitness tracking.",
      image: Demoimage,
    },
    {
      id: 19,
      title: "4K Television",
      price: "25999",
      category: "electronics",
      description: "Ultra HD 4K TV with vibrant colors and smart features.",
      image: Demoimage,
    },
    {
      id: 20,
      title: "Laptop",
      price: "45999",
      category: "electronics",
      description: "High-performance laptop for work and entertainment.",
      image: Demoimage,
    },
    {
      id: 21,
      title: "Tablet",
      price: "19999",
      category: "electronics",
      description: "Portable tablet with a large display for entertainment.",
      image: Demoimage,
    },
    {
      id: 22,
      title: "Bluetooth Speaker",
      price: "1499",
      category: "electronics",
      description: "Portable Bluetooth speaker with rich sound quality.",
      image: Demoimage,
    },
    {
      id: 23,
      title: "Gaming Console",
      price: "29999",
      category: "electronics",
      description: "Advanced gaming console with 4K support.",
      image: Demoimage,
    },
    {
      id: 24,
      title: "Digital Camera",
      price: "15999",
      category: "electronics",
      description: "Compact digital camera with HD photo and video capabilities.",
      image: Demoimage,
    },
    {
      id: 25,
      title: "External Hard Drive",
      price: "3999",
      category: "electronics",
      description: "1TB external hard drive for data storage.",
      image: Demoimage,
    },
    {
      id: 26,
      title: "Portable Charger",
      price: "899",
      category: "electronics",
      description: "Compact power bank with fast-charging capability.",
      image: Demoimage,
    },
    {
      id: 27,
      title: "Smart Home Assistant",
      price: "4999",
      category: "electronics",
      description: "Voice-activated smart assistant for home automation.",
      image: Demoimage,
    },
    {
      id: 28,
      title: "Electric Kettle",
      price: "899",
      category: "electronics",
      description: "Fast-boiling electric kettle with automatic shut-off.",
      image: Demoimage,
    },
    {
      id: 29,
      title: "Air Purifier",
      price: "6999",
      category: "electronics",
      description: "Efficient air purifier to remove indoor pollutants.",
      image: Demoimage,
    },
    {
      id: 30,
      title: "Wireless Mouse",
      price: "499",
      category: "electronics",
      description: "Smooth and responsive wireless mouse for computers.",
      image: Demoimage,
    },
  
    {
      id: 31,
      title: "Organic Flour",
      price: "55",
      category: "groceries",
      description: "100% organic wheat flour for healthy meals.",
      image: Demoimage,
    },
    {
      id: 32,
      title: "Olive Oil",
      price: "299",
      category: "groceries",
      description: "Extra virgin olive oil for cooking and salads.",
      image: Demoimage,
    },
    {
      id: 33,
      title: "Green Tea",
      price: "120",
      category: "groceries",
      description: "Refreshing green tea, packed with antioxidants.",
      image: Demoimage,
    },
    {
      id: 34,
      title: "Basmati Rice",
      price: "99",
      category: "groceries",
      description: "Long-grain basmati rice with a delicate aroma.",
      image: Demoimage,
    },
    {
      id: 35,
      title: "Almonds",
      price: "450",
      category: "groceries",
      description: "Crunchy almonds rich in protein and healthy fats.",
      image: Demoimage,
    },
    {
      id: 36,
      title: "Honey",
      price: "150",
      category: "groceries",
      description: "Natural honey, a perfect sweetener for your drinks.",
      image: Demoimage,
    },
    {
      id: 37,
      title: "Whole Wheat Pasta",
      price: "80",
      category: "groceries",
      description: "Healthy whole wheat pasta for wholesome meals.",
      image: Demoimage,
    },
    {
      id: 38,
      title: "Brown Sugar",
      price: "60",
      category: "groceries",
      description: "Unrefined brown sugar for healthier sweetness.",
      image: Demoimage,
    },
    {
      id: 39,
      title: "Oats",
      price: "90",
      category: "groceries",
      description: "Healthy and nutritious oats for breakfast.",
      image: Demoimage,
    },
    {
      id: 40,
      title: "Black Beans",
      price: "70",
      category: "groceries",
      description: "High-protein black beans for nutritious meals.",
      image: Demoimage,
    },
    {
      id: 41,
      title: "Coconut Oil",
      price: "200",
      category: "groceries",
      description: "Pure coconut oil for cooking and hair care.",
      image: Demoimage,
    },
    {
      id: 42,
      title: "Organic Spices Set",
      price: "350",
      category: "groceries",
      description: "Assorted organic spices for flavorful cooking.",
      image: Demoimage,
    },
    {
      id: 43,
      title: "Almond Milk",
      price: "120",
      category: "groceries",
      description: "Dairy-free almond milk for lactose-intolerant individuals.",
      image: Demoimage,
    },
    {
      id: 44,
      title: "Chia Seeds",
      price: "110",
      category: "groceries",
      description: "Nutrient-rich chia seeds for smoothies and salads.",
      image: Demoimage,
    },
    {
      id: 45,
      title: "Quinoa",
      price: "130",
      category: "groceries",
      description: "Protein-rich quinoa for a balanced diet.",
      image: Demoimage,
    },
  ]);
  
  
  return (
    <UserContext.Provider
      value={{
        products,
        setProducts,
        priceRange,
        setPriceRang,
        category,
        setCategory,
        cartItem,
        setCartItem,
        quantity,
        setQuantity,
      }}
    >
      {children}
    </UserContext.Provider>
  );
};

export default UserContextProvider;
